src/models/Journal.py
from main import db
from datetime import datetime
from flask_login import UserMixin


class Journal(UserMixin, db.Model):
    __tablename__ = "journal"

    id = db.Column(db.Integer, primary_key=True)
    journal_entry = db.Column(db.String())
    journal_date = db.Column(db.DateTime, default=datetime.now)
    user_id_fk = db.Column(db.Integer())

src/controllers/auth.py
from main import db
from flask import Blueprint, render_template, redirect, url_for, request, flash
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, logout_user, login_required
from models.User import User
from forms.forms import RegistrationForm


auth = Blueprint('auth', __name__)


@auth.route('/login')
def login():
    return render_template('login.html')


@auth.route('/login', methods=['POST'])
def login_post():
    email = request.form.get('email')
    password = request.form.get('password')
    remember = True if request.form.get('remember') else False

    user = User.query.filter_by(email=email).first()

    if not user or not check_password_hash(user.password, password):
        flash('Please check your login details and try again.')
        return redirect(url_for('auth.login'))

    login_user(user, remember=remember)
    return redirect(url_for('main.profile'))


@auth.route('/signup')
def signup():
    return render_template('signup.html')


@auth.route('/signup', methods=['POST'])
def signup_post():
    try:
        form = RegistrationForm()
        if form.validate():
            email = request.form.get('email')
            name = request.form.get('name')
            password = request.form.get('password')
            new_user = User(email=email, name=name,
                            password=generate_password_hash(
                                password, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            flash('Thanks for registering. Please Log in below.')
            return redirect(url_for('main.profile'))
    except Exception:
        flash('Email already registered')
        render_template('signup.html', form=form, error=form.errors)

    return render_template('signup.html', form=form, error=form.errors)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))

src/controllers/journal.py
from main import db
from models.Journal import Journal
from flask import Blueprint, render_template, redirect, url_for, request
from flask_login import login_required, current_user
from forms.forms import AddJournalEntryForm
from datetime import datetime
from sqlalchemy import func


journal = Blueprint("journal", __name__, url_prefix="/journal")


@journal.route('/new_entry', methods=["GET", "POST"])
@login_required
def journal_entry_create():
    form = AddJournalEntryForm()
    if form.validate_on_submit():
        journal = Journal()
        journal.journal_entry = form.journal_entry.data
        user_id = current_user._get_current_object()
        journal.user_id_fk = user_id.id
        db.session.add(journal)
        db.session.commit()

    return redirect(url_for('journal.get_journal_entries'))


@journal.route("/journal-entries", methods=["GET"])
@login_required
def get_journal_entries():
    user_id = current_user._get_current_object()
    user = user_id.id
    journal_entries = Journal.query.filter_by(
        user_id_fk=user).order_by(Journal.journal_date.desc()).all()
    return render_template('journal_entries.html',
                           journal_entries=journal_entries,
                           name=current_user.name)


@journal.route("/journal-entry/<int:journal_id>", methods=["GET"])
@login_required
def get_journal_entry(journal_id):
    user_id = current_user._get_current_object()
    user = user_id.id
    journal_entry = Journal.query.filter_by(user_id_fk=user,
                                            id=journal_id).first()
    return render_template('journal_entry.html', journal_entry=journal_entry)


@journal.route('/query', methods=['GET'])
def query_journal():
    try:
        user_id = current_user._get_current_object()
        user = user_id.id
        entry = request.args.get('entry')
        datetime_object = datetime.strptime(entry, "%Y-%m-%d")
        journal_entries = db.session.query(Journal).filter(
            func.date(Journal.journal_date) == datetime_object).filter(
                Journal.user_id_fk == user).all()

        return render_template('journal_entries.html',
                               journal_entries=journal_entries,
                               name=current_user.name)
    except (Exception):
        return render_template('journal_entries.html')


@journal.route("/journal-entries/<int:journal_id>", methods=["POST"])
@login_required
def delete_journal_entry(journal_id):
    user_id = current_user._get_current_object()
    user = user_id.id
    journal_entry = Journal.query.filter_by(user_id_fk=user,
                                            id=journal_id).first()
    db.session.delete(journal_entry)
    db.session.commit()
    return redirect(url_for('journal.get_journal_entries'))


@journal.route("/journal-entry/update/<int:journal_id>", methods=["POST"])
@login_required
def update_single_journal_entry(journal_id):
    user_id = current_user._get_current_object()
    user = user_id.id
    update_journal_entry = Journal.query.filter_by(user_id_fk=user,
                                                   id=journal_id).first()
    update_journal_entry.journal_entry = request.form.get("journal_entry")
    db.session.commit()
    return render_template('journal_entry.html',
                           journal_entry=update_journal_entry)

src/controllers/main.py
from main import db
from flask import Blueprint, render_template, redirect
from flask import url_for, request, flash
from flask_login import login_required, current_user
from werkzeug.security import generate_password_hash


main = Blueprint('main', __name__)


@main.route('/')
def index():
    return render_template('index.html')


@main.route('/profile')
@login_required
def profile():
    return render_template('profile.html', name=current_user.name)


@main.route('/profile', methods=["POST"])
@login_required
def user_password_change():
    user_id = current_user._get_current_object()
    password = request.form.get('password')
    if len(password) < 6:
        flash('Password not valid')
        return redirect(url_for('main.profile'))
    else:
        user_id.password = generate_password_hash(password, method='sha256')
        db.session.commit()
        flash('Password changed')

    return redirect(url_for('main.profile'))

src/controllers/problemareas.py
from main import db
from models.ProblemArea import ProblemArea
from flask import Blueprint, render_template
from flask import redirect, url_for
from flask_login import login_required, current_user
from forms.forms import AddProblemAreaEntryForm


problem_area = Blueprint("problem_area", __name__, url_prefix="/problem_area")


@problem_area.route('/new_entry', methods=["GET", "POST"])
@login_required
def problem_area_entry_create():
    form = AddProblemAreaEntryForm()
    if form.validate_on_submit():
        problem_area = ProblemArea()
        problem_area.problem_area_entry = form.problem_area_entry.data
        user_id = current_user._get_current_object()
        problem_area.user_id_fk = user_id.id
        db.session.add(problem_area)
        db.session.commit()

    return redirect(url_for('problem_area.get_problem_area_entries'))


@problem_area.route("/problem_area_entries", methods=["GET"])
@login_required
def get_problem_area_entries():
    user_id = current_user._get_current_object()
    user = user_id.id
    problem_area_entries = ProblemArea.query.filter_by(
        user_id_fk=user).order_by(ProblemArea.problem_area_date.desc()).all()
    return render_template('problem_area_entries.html',
                           problem_area_entries=problem_area_entries,
                           name=current_user.name)


@problem_area.route("/problem_area_entry/<int:problem_area_id>",
                    methods=["GET"])
@login_required
def get_problem_area_entry(problem_area_id):
    user_id = current_user._get_current_object()
    user = user_id.id
    problem_area_entry = ProblemArea.query.filter_by(
        user_id_fk=user, id=problem_area_id).first()
    return render_template('problem_area_entry.html',
                           problem_area_entry=problem_area_entry)


@problem_area.route("/problem_area_entries/<int:problem_area_id>",
                    methods=["POST"])
@login_required
def delete_problem_area_entry(problem_area_id):
    user_id = current_user._get_current_object()
    user = user_id.id
    problem_area_entry = ProblemArea.query.filter_by(
        user_id_fk=user,
        id=problem_area_id).first()
    db.session.delete(problem_area_entry)
    db.session.commit()
    return redirect(url_for('problem_area.get_problem_area_entries'))


@problem_area.route("/problem_area_entry/update/<int:problem_area_id>",
                    methods=["POST"])
@login_required
def update_single_problem_area_entry(problem_area_id):
    form = AddProblemAreaEntryForm()
    user_id = current_user._get_current_object()
    user = user_id.id
    update_problem_area_entry = ProblemArea.query.filter_by(
        user_id_fk=user,
        id=problem_area_id).first()
    update_problem_area_entry.problem_area_entry = form.problem_area_entry.data
    db.session.commit()
    return render_template('problem_area_entry.html',
                           problem_area_entry=update_problem_area_entry)

src/controllers/skills.py
from main import db
from models.Skill import Skill
from flask import Blueprint, render_template, redirect, url_for
from flask_login import login_required, current_user
from forms.forms import AddSkillEntryForm


skill = Blueprint("skill", __name__, url_prefix="/skill")


@skill.route('/new_entry', methods=["GET", "POST"])
@login_required
def skill_entry_create():
    form = AddSkillEntryForm()
    if form.validate_on_submit():
        skill = Skill()
        skill.skill_entry = form.skill_entry.data
        user_id = current_user._get_current_object()
        skill.user_id_fk = user_id.id
        db.session.add(skill)
        db.session.commit()

    return redirect(url_for('skill.get_skill_entries'))


@skill.route("/skill_entries", methods=["GET"])
@login_required
def get_skill_entries():
    user_id = current_user._get_current_object()
    user = user_id.id
    skill_entries = Skill.query.filter_by(
        user_id_fk=user).order_by(Skill.skill_date.desc()).all()
    return render_template('skill_entries.html',
                           skill_entries=skill_entries,
                           name=current_user.name)


@skill.route("/skill_entry/<int:skill_id>", methods=["GET"])
@login_required
def get_skill_entry(skill_id):
    user_id = current_user._get_current_object()
    user = user_id.id
    skill_entry = Skill.query.filter_by(user_id_fk=user,
                                        id=skill_id).first()
    return render_template('skill_entry.html',
                           skill_entry=skill_entry)


@skill.route("/skill_entries/<int:skill_id>", methods=["POST"])
@login_required
def delete_skill_entry(skill_id):
    user_id = current_user._get_current_object()
    user = user_id.id
    skill_entry = Skill.query.filter_by(user_id_fk=user,
                                        id=skill_id).first()
    db.session.delete(skill_entry)
    db.session.commit()
    return redirect(url_for('skill.get_skill_entries'))


@skill.route("/skill_entry/update/<int:skill_id>", methods=["POST"])
@login_required
def update_single_skill_entry(skill_id):
    form = AddSkillEntryForm()
    user_id = current_user._get_current_object()
    user = user_id.id
    update_skill_entry = Skill.query.filter_by(
        user_id_fk=user, id=skill_id).first()
    update_skill_entry.skill_entry = form.skill_entry.data
    db.session.commit()
    return render_template('skill_entry.html',
                           skill_entry=update_skill_entry)

src/templates/base.html
<!-- templates/base.html -->

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>My Mood Diary</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
  
    <section class="hero is-primary has-background-link is-fullheight">
        <div class="hero-head">
              <nav class="navbar" role="navigation" aria-label="main navigation">
                <div class="navbar-brand">
              
                  <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                  </a>
                </div>
              
                <div id="navbarBasicExample" class="navbar-menu">
                  <div class="navbar-start">
                    <div class="navbar-start">
                      <a class="navbar-item" href="{{ url_for('main.index') }}">
                        Home
                      </a>
                      {% if current_user.is_authenticated %}
                      <a class="navbar-item" href="{{ url_for('main.profile') }}">
                          Profile
                      </a>
                      <a href="{{ url_for('journal.get_journal_entries') }}" class="navbar-item">
                          My Journal
                      </a>
                      <a href="{{ url_for('skill.get_skill_entries') }}" class="navbar-item">
                        My Skills
                    </a>
                    <a href="{{ url_for('problem_area.get_problem_area_entries') }}" class="navbar-item">
                      My Problem Areas
                  </a>
                      {% endif %}
                      </div>
                    </div>
                  </div>
              
                  <div class="navbar-end">
                    <div class="navbar-item">
                      <div class="buttons">
                        {% if current_user.is_anonymous %}
                        <a class="button is-primary" href="{{ url_for('auth.signup') }}">
                            <strong>Sign up</strong>
                        </a>  
                        <a class="button is-light" href="{{ url_for('auth.login') }}">
                          Log in
                        </a>
                        {% endif %} 
                        {% if current_user.is_authenticated %}
                        <a href="{{ url_for('auth.logout') }}" class="navbar-item">
                            Logout
                        </a>
                        {% endif %}
                      </div>
                    </div>
                  </div>
                </div>
              </nav>
        <div class="hero-body">
            <div class="container has-text-centered">
               {% block content %}
               {{ title }}
               {% endblock %}
            </div>
        </div>
    </section>
<script>
document.addEventListener('DOMContentLoaded', () => {

// Get all "navbar-burger" elements
const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

// Check if there are any navbar burgers
if ($navbarBurgers.length > 0) {

  // Add a click event on each of them
  $navbarBurgers.forEach( el => {
    el.addEventListener('click', () => {

      // Get the target from the "data-target" attribute
      const target = el.dataset.target;
      const $target = document.getElementById(target);

      // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
      el.classList.toggle('is-active');
      $target.classList.toggle('is-active');

    });
  });
}

});

</script>

  </body>

</html>


src/templates/index.html
<!-- templates/index.html -->

{% extends "base.html" %}

{% block content %}
<h1 class="title">
  My Mood Diary
</h1>
<h2 class="subtitle">
  An online application to track your mood and other habits.
</h2>
{% endblock %}

src/templates/journal_entries.html
<!-- templates/journal_entries.html -->

{% extends "base.html" %}

{% block content %}
<section class="hero is-large"  >
    <div class="hero-body" style="background-image: url(https://mood-diary-fullstack.s3-ap-southeast-2.amazonaws.com/psych-1.jpg); width:100%; height: 400px; margin:auto; background-size: cover; opacity: 0.8; background-position: center center; background-repeat: no-repeat;" >
  
      <p class="title is-size-1 has-text-weight-bold" style="transform:translateY(-50%); top: 50%;">
        My Journal
      </p>
    </div>
  </section>

<div class="has-text-justified">
    <p>
    Thoughts, emotions and behaviours are all intertwined whereby negative thoughts can trigger negative behaviours. A more holistic approach is usually implemented by tracking these three areas i.e. negative thoughts, general mood ratings and problem behaviours.
    </p>
    <br>
    <p>
    Tracking mood, thoughts and behaviours has been shown to increase insight, motivation and willingness to change. Skills are designed at the individual level to replace the negative moods, thoughts and behaviours. 
    </p>
    <br>
    </div>
<form method="POST" action="/journal/new_entry">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
    <div class="field">
        <div class="control">
            <textarea class="textarea" name="journal_entry" placeholder="Add journal entry"></textarea>
        </div>
    </div>
    <button class="button is-block is-info is-large">Add entry</button>
</form>


<form action="{{  url_for('journal.query_journal') }}"  method="GET">
    <label for="entry">Select the Date to see all entries of that day:</label>
    <input type="date" id="entry" name="entry">
    <br>
    <div class="buttons is-centered">
    <input class="button is-info is-small box has-text-centered" type="submit" value="Submit">
    </div>
  </form>

<br>
{% for journal_entry in journal_entries %}
<div class="box">
<div class="columns has-text-left">
    <div class="column has-text-link">
        <a href="{{  url_for('journal.get_journal_entry', journal_id=journal_entry.id) }}">
            {{ journal_entry.journal_entry }}
        </a>
    </div>
    <div class="column">
             Date of entry:
             {{ journal_entry.journal_date.strftime('%d-%m-%Y') }}
        </div>
        <div class="column">
            Time of entry:
            {{ journal_entry.journal_date.strftime('%H:%m  %p') }}
       </div>
    <div class="column">
        <form action="{{ url_for('journal.delete_journal_entry', journal_id=journal_entry.id) }}" method="POST">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
            <input class="button is-block is-info is-small box has-text-centered" type=submit value=Delete>
        </form>
    </div>
  </div>
</div>
{% else %}
<br>
<div class="mgt-medium">
<div class="notification is-danger">
    <p>No entries recorded</p>
</div>
</div>
  {% endfor %}


{% endblock %}

src/templates/journal_entry.html
<!-- templates/journal_entry.html -->

{% extends "base.html" %}

{% block content %}


<div class="box">
<div class="columns">
    <div class="column" action="{{ url_for('journal.get_journal_entry', journal_id=journal_entry.id) }}" method="GET">
        {{ journal_entry.journal_entry }}
    </div>
    <div class="column">
             Date of entry:
             {{ journal_entry.journal_date.strftime('%d-%m-%Y') }}
        </div>
    <div class="column">
        <form action="{{ url_for('journal.update_single_journal_entry', journal_id=journal_entry.id) }}" method="POST">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                    <input class="input" type="text" name="journal_entry" value="{{ journal_entry.journal_entry }}">
                    <button class="button is-block is-info is-medium">Edit entry</button>
        </form>
    </div>
    <div class="column">
        <form action="{{ url_for('journal.delete_journal_entry', journal_id=journal_entry.id) }}" method="POST">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
            <input class="button is-block is-info is-medium box has-text-centered" type=submit value=Delete>
        </form>
    </div>
  </div>
</div>


{% endblock %}

src/templates/problem_area_entries.html
<!-- templates/problem_area_entries.html -->

{% extends "base.html" %}

{% block content %}
<section class="hero is-large"  >
    <div class="hero-body" style="background-image: url(https://mood-diary-fullstack.s3-ap-southeast-2.amazonaws.com/psych-1.jpg); width:100%; height: 400px; margin:auto; background-size: cover; opacity: 0.8; background-position: center center; background-repeat: no-repeat;" >
  
      <p class="title is-size-1 has-text-weight-bold" style="transform:translateY(-50%); top: 50%;">
        Problem Areas
      </p>
    </div>
  </section>

<div class="has-text-justified">
    <p>
    Thoughts, emotions and behaviours are all intertwined whereby negative thoughts can trigger negative behaviours. A more holistic approach is usually implemented by tracking these three areas i.e. negative thoughts, general mood ratings and problem behaviours.
    </p>
    <br>
    <p>
    Tracking mood, thoughts and behaviours has been shown to increase insight, motivation and willingness to change. Skills are designed at the individual level to replace the negative moods, thoughts and behaviours. 
    </p>
    <br>
    </div>
<form method="POST" action="/problem_area/new_entry">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
    <div class="field">
        <div class="control">
            <textarea class="textarea" name="problem_area_entry" placeholder="Add Problem Area"></textarea>
        </div>
    </div>
    <button class="button is-block is-info is-large">Add entry</button>
</form>
<br>
{% for problem_area_entry in problem_area_entries %}
<div class="box">
<div class="columns has-text-left">
    <div class="column has-text-link">
        <a href="{{  url_for('problem_area.get_problem_area_entry', problem_area_id=problem_area_entry.id) }}">
            {{ problem_area_entry.problem_area_entry }}
        </a>
    </div>
    <div class="column">
             Date of entry:
             {{ problem_area_entry.problem_area_date.strftime('%d-%m-%Y') }}
        </div>
        <div class="column">
            Time of entry:
            {{ problem_area_entry.problem_area_date.strftime('%H:%m  %p') }}
       </div>
    <div class="column">
        <form action="{{ url_for('problem_area.delete_problem_area_entry', problem_area_id=problem_area_entry.id) }}" method="POST">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
            <input class="button is-block is-info is-medium box has-text-centered" type=submit value=Delete>
        </form>
    </div>
  </div>
</div>
<br>
{% else %}
<div class="mgt-medium">
<div class="notification is-danger">
    <p>No problem areas recorded</p>
</div>
</div>
  {% endfor %}

{% endblock %}

src/templates/problem_area_entry.html
<!-- templates/problem_area_entry.html -->

{% extends "base.html" %}

{% block content %}


<div class="box">
<div class="columns">
    <div class="column" action="{{ url_for('problem_area.get_problem_area_entry', problem_area_id=problem_area_entry.id) }}" method="GET">
        {{ problem_area_entry.problem_area_entry }}
    </div>
    <div class="column">
             Date of entry:
             {{ problem_area_entry.problem_area_date.strftime('%d-%m-%Y') }}
        </div>
    <div class="column">
        <form action="{{ url_for('problem_area.update_single_problem_area_entry', problem_area_id=problem_area_entry.id) }}" method="POST">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                    <input class="input" type="text" name="problem_area_entry" value="{{ problem_area_entry.problem_area_entry }}">
                    <button class="button is-block is-info is-medium">Edit entry</button>
        </form>
    </div>
    <div class="column">
        <form action="{{ url_for('problem_area.delete_problem_area_entry', problem_area_id=problem_area_entry.id) }}" method="POST">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
            <input class="button is-block is-info is-medium box has-text-centered" type=submit value=Delete>
        </form>
    </div>
  </div>
</div>


{% endblock %}

src/templates/profile.html
<!-- templates/profile.html -->

{% extends "base.html" %}

{% block content %}
<h1 class="title">
  Welcome, {{ name }}!
</h1>

<div class="column is-4 is-offset-4">
  <h4 class="title">Add psychologist details</h4>
  <div class="box">
      {% with messages = get_flashed_messages() %}
      {% if messages %}
          <div class="notification is-danger">
              {{ messages[0] }}
          </div>
      {% endif %}
      {% endwith %}
      <form method="POST" action="{{ url_for('psychologist.post_psychologist_details') }}">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
          <div class="field">
              <div class="control">
                  <input class="input is-large" name="name" placeholder="Add Psychologist Name">
              </div>
          </div>
          <div class="field">
            <div class="control">
              <input class="input is-large" name="email" placeholder="Add Psychologist email">
            </div>
        </div>
          <button class="button is-block is-info is-large is-fullwidth">Add Psychologist</button>
      </form>
  </div>
</div>

{% for psychologists in psychologists %}
<div class="box">
<div class="columns has-text-left">
    <div class="column has-text-link">
        <a href="{{  url_for('psychologist.get_all_psychologists', psychologists=psychologists.id) }}">
            {{ psychologists.name }}
        </a>
    </div>
    <div class="column">
             {{ psychologists.email }}
        </div>
  </div>
</div>

  {% endfor %}

  <div class="column is-4 is-offset-4">
    <h3 class="title">Change Password</h3>
    <div class="box">
        {% if error %}<p class=error><strong>Error:</strong> {{ error }}{% endif %}
          {% with messages = get_flashed_messages() %}
          {% if messages %}
              <div class="notification is-danger">
                  {{ messages[0] }}
              </div>
          {% endif %}
          {% endwith %}
        <form action="{{ url_for('main.user_password_change') }}"  method="POST">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="password" name="password" placeholder="Password">
                </div>
            </div>

            <button class="button is-block is-info is-large is-fullwidth">Change</button>
        </form>
    </div>
</div>
{% endblock %} 

src/templates/skill_entries.html
<!-- templates/skill_entries.html -->

{% extends "base.html" %}

{% block content %}


  <section class="hero is-large"  >
    <div class="hero-body" style="background-image: url(https://mood-diary-fullstack.s3-ap-southeast-2.amazonaws.com/psych-1.jpg); width:100%; height: 400px; margin:auto; background-size: cover; opacity: 0.8; background-position: center center; background-repeat: no-repeat;" >
  
      <p class="title is-size-1 has-text-weight-bold" style="transform:translateY(-50%); top: 50%;">
        Skills
      </p>
    </div>
  </section>
<div class="has-text-justified">
<p>
Thoughts, emotions and behaviours are all intertwined whereby negative thoughts can trigger negative behaviours. 
A more holistic approach is usually implemented by tracking these three areas i.e. negative thoughts, general mood ratings and problem behaviours.
</p>
<br>
<p>
Tracking mood, thoughts and behaviours has been shown to increase insight, motivation and willingness to change. 
Skills are designed at the individual level to replace the negative moods, thoughts and behaviours. 
</p>
<br>
</div>
<form method="POST" action="/skill/new_entry">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
    <div class="field">
        <div class="control">
            <textarea class="textarea" name="skill_entry" placeholder="Add skill entry"></textarea>
        </div>
    </div>
    <button class="button is-block is-info is-large">Add entry</button>
</form>

<br>
{% for skill_entry in skill_entries %}
<div class="box has-background-light">
<div class="columns has-text-left">
    <div class="column has-text-link">
        <a href="{{  url_for('skill.get_skill_entry', skill_id=skill_entry.id) }}">
            {{ skill_entry.skill_entry }}
        </a>
    </div>
    <div class="column">
             Date of entry:
             {{ skill_entry.skill_date.strftime('%d-%m-%Y') }}
        </div>
        <div class="column">
            Time of entry:
            {{ skill_entry.skill_date.strftime('%H:%m  %p') }}
       </div>
    <div class="column">
        <form action="{{ url_for('skill.delete_skill_entry', skill_id=skill_entry.id) }}" method="POST">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
            <input class="button is-block is-info is-small box has-text-centered" type=submit value=Delete>
        </form>
    </div>
  </div>
</div>
{% else %}
<br>
<div class="mgt-medium">
<div class="notification is-danger">
    <p>No skills recorded</p>
</div>
</div>
  {% endfor %}


{% endblock %}

src/templates/skill_entry.html
<!-- templates/skill_entry.html -->

{% extends "base.html" %}

{% block content %}


<div class="box">
<div class="columns">
    <div class="column" action="{{ url_for('skill.get_skill_entry',skill_id=skill_entry.id) }}" method="GET">
        {{skill_entry.skill_entry }}
    </div>
    <div class="column">
             Date of entry:
             {{skill_entry.skill_date.strftime('%d-%m-%Y') }}
        </div>
    <div class="column">
        <form action="{{ url_for('skill.update_single_skill_entry', skill_id=skill_entry.id) }}" method="POST">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                    <input class="input" type="text" name="skill_entry" value="{{skill_entry.skill_entry }}">
                    <button class="button is-block is-info is-medium">Edit entry</button>
        </form>
    </div>
    <div class="column">
        <form action="{{ url_for('skill.delete_skill_entry',skill_id=skill_entry.id) }}" method="POST">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
            <input class="button is-block is-info is-medium box has-text-centered" type=submit value=Delete>
        </form>
    </div>
  </div>
</div>


{% endblock %}